const { exif } = require('./exif.js');
const { data } = require('./data.js');
const { thumbnails } = require('./thumbnails.js');
const { ocr } = require('./ocr.js');
const { fileops } = require('./fileops.js')
const { AI } = require('./AI.js')

exports.tasks = {

    // adds new media to the database by copying it to the temp
    // directory and creating the initial record in the media table
    addMedia: async (mediaFilename) => {
        console.log(`[ ] Adding media ${mediaFilename}`)
        return await data.addMedia(mediaFilename)
    },

    // extracts and saves exif data for the specified media
    saveMetadata: exif.saveMetadata,

    // relocates media from the temp folder to its final place
    relocateMedia: fileops.relocateMedia,
    
    // creates a thumbnail for the specified media
    makeThumbnail: thumbnails.makeThumbnail,

    // uses tesseract to attempt OCR in the photos being uploaded
    runOCR: ocr.run,

    // autogenerated tags based on AI model
    generateAITags: AI.generateTags
}